import { StyleSheet, Dimensions } from 'react-native';
import { Theme } from '../../constants/theme';

const { width } = Dimensions.get('window');

// Windows XP Corporate color palette
const XP = {
  titleBar: '#0a246a',
  titleBarLight: '#0854cb',
  windowBg: '#ece9d8',
  windowBgAlt: '#d4d0c8',
  buttonFace: '#ece9d8',
  buttonHighlight: '#ffffff',
  buttonShadow: '#aca899',
  buttonDarkShadow: '#716f64',
  textDark: '#000000',
  textGray: '#555555',
  textLight: '#ffffff',
  activeBorder: '#0054e3',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: XP.windowBg,
  },
  blackoutOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000',
    zIndex: 50,
  },

  // Windows XP Title Bar
  titleBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: XP.titleBar,
    paddingVertical: 6,
    paddingHorizontal: 8,
    // Gradient-like effect with border
    borderBottomWidth: 1,
    borderBottomColor: XP.titleBarLight,
  },
  titleBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  titleBarIcon: {
    width: 16,
    height: 16,
    backgroundColor: '#ffa500',
    borderRadius: 2,
  },
  titleBarText: {
    fontFamily: 'Courier',
    fontSize: 13,
    fontWeight: '700',
    color: XP.textLight,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  titleBarButtons: {
    flexDirection: 'row',
    gap: 2,
  },
  titleBarButton: {
    width: 21,
    height: 21,
    backgroundColor: XP.buttonFace,
    justifyContent: 'center',
    alignItems: 'center',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: XP.buttonHighlight,
    borderLeftColor: XP.buttonHighlight,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderBottomColor: XP.buttonDarkShadow,
    borderRightColor: XP.buttonShadow,
    borderRadius: 3,
  },
  titleBarButtonClose: {
    backgroundColor: '#c45a5a',
  },
  titleBarButtonText: {
    fontFamily: 'Courier',
    fontSize: 14,
    fontWeight: '700',
    color: XP.textDark,
    marginTop: -2,
  },

  // Status bar (phone-like header)
  statusBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  statusTime: {
    fontFamily: 'Courier',
    fontSize: 14,
    color: '#4a5d4a',
    fontWeight: '600',
  },
  statusRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  signalBars: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 2,
  },
  signalBar: {
    width: 3,
    backgroundColor: '#4a5d4a',
  },
  signalBar1: { height: 4 },
  signalBar2: { height: 6 },
  signalBar3: { height: 8 },
  signalBar4: { height: 10 },
  batteryText: {
    fontFamily: 'Courier',
    fontSize: 12,
    color: '#4a5d4a',
  },

  // Phase 1: Menu Style - Windows XP Corporate
  menuContainer: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    // Subtle inset panel effect
    borderWidth: 2,
    borderTopColor: XP.buttonShadow,
    borderLeftColor: XP.buttonShadow,
    borderBottomColor: XP.buttonHighlight,
    borderRightColor: XP.buttonHighlight,
    margin: 4,
    backgroundColor: XP.windowBg,
  },
  menuContent: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },

  // Logo Container
  logoContainer: {
    width: 180,
    height: 180,
    backgroundColor: XP.windowBgAlt,
    borderRadius: 4,
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
    // Classic 3D inset border
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderTopColor: XP.buttonShadow,
    borderLeftColor: XP.buttonDarkShadow,
    borderBottomWidth: 2,
    borderRightWidth: 2,
    borderBottomColor: XP.buttonHighlight,
    borderRightColor: XP.buttonHighlight,
    overflow: 'hidden',
  },
  logoImage: {
    width: 170,
    height: 170,
  },

  menuTitle: {
    fontFamily: Theme.fonts.mono,
    fontSize: 48,
    fontWeight: '700',
    color: XP.titleBar,
    letterSpacing: 8,
    marginBottom: 8,
    textAlign: 'center',
  },
  menuSubtitle: {
    fontFamily: 'Courier',
    fontSize: 11,
    color: XP.textGray,
    letterSpacing: 0.5,
    marginBottom: 16,
    textAlign: 'center',
    paddingHorizontal: 20,
  },

  divider: {
    width: 200,
    height: 2,
    backgroundColor: XP.buttonShadow,
    marginVertical: 16,
    // 3D groove effect
    borderTopWidth: 1,
    borderTopColor: XP.buttonDarkShadow,
    borderBottomWidth: 1,
    borderBottomColor: XP.buttonHighlight,
  },

  menuSlogan: {
    fontFamily: 'Courier',
    fontSize: 12,
    fontStyle: 'italic',
    color: XP.titleBar,
    marginBottom: 24,
    textAlign: 'center',
  },

  menuVersion: {
    fontFamily: 'Courier',
    fontSize: 10,
    color: XP.textGray,
    marginBottom: 32,
  },

  // Classic Windows XP 3D Button
  startButton: {
    width: 200,
    height: 40,
    backgroundColor: XP.buttonFace,
    borderRadius: 0,
    justifyContent: 'center',
    alignItems: 'center',
    // Classic raised bevel
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderTopColor: XP.buttonHighlight,
    borderLeftColor: XP.buttonHighlight,
    borderBottomWidth: 2,
    borderRightWidth: 2,
    borderBottomColor: XP.buttonDarkShadow,
    borderRightColor: XP.buttonShadow,
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 4,
  },
  startButtonInner: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: XP.buttonFace,
  },
  startButtonText: {
    fontFamily: 'Courier',
    fontSize: 13,
    fontWeight: '700',
    color: XP.textDark,
    letterSpacing: 1,
  },
  // Pressed states - classic Windows pressed button
  startButtonPressed: {
    borderTopColor: XP.buttonDarkShadow,
    borderLeftColor: XP.buttonShadow,
    borderBottomColor: XP.buttonHighlight,
    borderRightColor: XP.buttonHighlight,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    elevation: 0,
  },
  startButtonInnerPressed: {
    backgroundColor: XP.windowBgAlt,
  },
  startButtonTextPressed: {
    color: XP.textDark,
  },

  settingsButton: {
    marginTop: 12,
    paddingVertical: 8,
    paddingHorizontal: 20,
    backgroundColor: XP.buttonFace,
    borderRadius: 0,
    // Classic raised bevel
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: XP.buttonHighlight,
    borderLeftColor: XP.buttonHighlight,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderBottomColor: XP.buttonDarkShadow,
    borderRightColor: XP.buttonShadow,
  },
  settingsButtonPressed: {
    borderTopColor: XP.buttonDarkShadow,
    borderLeftColor: XP.buttonShadow,
    borderBottomColor: XP.buttonHighlight,
    borderRightColor: XP.buttonHighlight,
    backgroundColor: XP.windowBgAlt,
  },
  settingsButtonText: {
    fontFamily: 'Courier',
    fontSize: 11,
    color: XP.textDark,
  },

  // Continue Button - More prominent than Start
  continueButton: {
    width: 200,
    height: 52,
    backgroundColor: XP.titleBar,
    borderRadius: 0,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderTopColor: XP.titleBarLight,
    borderLeftColor: XP.titleBarLight,
    borderBottomWidth: 2,
    borderRightWidth: 2,
    borderBottomColor: '#041540',
    borderRightColor: '#052a6a',
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 6,
  },
  continueButtonInner: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: XP.titleBar,
  },
  continueButtonText: {
    fontFamily: 'Courier',
    fontSize: 14,
    fontWeight: '700',
    color: XP.textLight,
    letterSpacing: 2,
  },
  continueSubtext: {
    fontFamily: 'Courier',
    fontSize: 10,
    color: '#7fb8d8',
    marginTop: 2,
  },
  continueButtonPressed: {
    borderTopColor: '#041540',
    borderLeftColor: '#052a6a',
    borderBottomColor: XP.titleBarLight,
    borderRightColor: XP.titleBarLight,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    elevation: 0,
  },
  continueButtonInnerPressed: {
    backgroundColor: '#052a6a',
  },
  continueButtonTextPressed: {
    color: '#b8d8f0',
  },
  continueSubtextPressed: {
    color: '#5a8aaa',
  },

  // Confirmation Modal - Windows XP Dialog
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  confirmModal: {
    width: 300,
    backgroundColor: XP.windowBg,
    borderWidth: 2,
    borderTopColor: XP.buttonHighlight,
    borderLeftColor: XP.buttonHighlight,
    borderBottomColor: XP.buttonDarkShadow,
    borderRightColor: XP.buttonShadow,
  },
  confirmTitleBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: XP.titleBar,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  confirmTitleText: {
    fontFamily: 'Courier',
    fontSize: 12,
    fontWeight: '700',
    color: XP.textLight,
  },
  confirmCloseButton: {
    fontFamily: 'Courier',
    fontSize: 18,
    fontWeight: '700',
    color: XP.textLight,
  },
  confirmContent: {
    padding: 20,
    alignItems: 'center',
  },
  confirmIcon: {
    fontSize: 32,
    marginBottom: 12,
  },
  confirmMessage: {
    fontFamily: 'Courier',
    fontSize: 12,
    color: XP.textDark,
    textAlign: 'center',
    lineHeight: 18,
  },
  confirmQuestion: {
    fontFamily: 'Courier',
    fontSize: 12,
    fontWeight: '700',
    color: XP.textDark,
    marginTop: 12,
  },
  confirmButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
    paddingBottom: 16,
  },
  confirmButton: {
    width: 80,
    height: 28,
    backgroundColor: XP.buttonFace,
    justifyContent: 'center',
    alignItems: 'center',
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderTopColor: XP.buttonHighlight,
    borderLeftColor: XP.buttonHighlight,
    borderBottomWidth: 2,
    borderRightWidth: 2,
    borderBottomColor: XP.buttonDarkShadow,
    borderRightColor: XP.buttonShadow,
  },
  confirmButtonPressed: {
    borderTopColor: XP.buttonDarkShadow,
    borderLeftColor: XP.buttonShadow,
    borderBottomColor: XP.buttonHighlight,
    borderRightColor: XP.buttonHighlight,
    backgroundColor: XP.windowBgAlt,
  },
  confirmButtonText: {
    fontFamily: 'Courier',
    fontSize: 12,
    color: XP.textDark,
  },

  // Footer Bar - Windows XP status bar style
  footerBar: {
    width: '100%',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: XP.windowBgAlt,
    borderTopWidth: 1,
    borderTopColor: XP.buttonShadow,
    alignItems: 'center',
  },
  footerText: {
    fontFamily: 'Courier',
    fontSize: 9,
    color: XP.textGray,
    textAlign: 'center',
  },
  footerSubtext: {
    fontFamily: 'Courier',
    fontSize: 8,
    color: XP.buttonShadow,
    marginTop: 2,
    letterSpacing: 1,
  },

  // Phase 2: Clean Messaging UI
  onboardContainer: {
    flex: 1,
    paddingTop: 16,
    paddingHorizontal: 20,
  },
  
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(74, 93, 74, 0.1)',
  },
  avatarContainer: {
    position: 'relative',
    marginRight: 12,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#c5cbc0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontFamily: 'Courier',
    fontSize: 18,
    fontWeight: '700',
    color: '#4a5d4a',
  },
  onlineIndicator: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#6a8a6a',
    borderWidth: 2,
    borderColor: '#d8dcd0',
  },
  headerText: {
    flex: 1,
  },
  contactName: {
    fontFamily: 'Courier',
    fontSize: 16,
    fontWeight: '700',
    color: '#3a4a3a',
    letterSpacing: 1,
  },
  contactStatus: {
    fontFamily: 'Courier',
    fontSize: 9,
    color: '#6a8a6a',
    letterSpacing: 1,
    marginTop: 2,
  },
  timestampContainer: {
    alignItems: 'center',
    marginBottom: 10,
  },
  timestampText: {
    fontFamily: 'Courier',
    fontSize: 11,
    color: '#8a9a8a',
    backgroundColor: '#d8dcd0',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 10,
    overflow: 'hidden',
  },

  messagesArea: {
    flex: 1,
  },
  
  messageBubble: {
    alignSelf: 'flex-start',
    backgroundColor: '#e1e5da', // Slightly lighter than background
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 15,
    borderTopLeftRadius: 2,
    marginBottom: 12,
    maxWidth: '85%',
    // Skeuomorphic depth
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  messageText: {
    fontFamily: 'Courier',
    fontSize: 14,
    color: '#3a4a3a',
    lineHeight: 18,
  },
  messageTime: {
    fontFamily: 'Courier',
    fontSize: 9,
    color: '#8a9a8a',
  },
  messageFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 4,
    gap: 6,
  },
  readReceipt: {
    fontFamily: 'Courier',
    fontSize: 9,
    color: '#6a8a6a',
    fontWeight: '600',
  },
  // Sent messages (player's replies)
  messageBubbleSent: {
    alignSelf: 'flex-end',
    backgroundColor: '#6a8a6a',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 2,
  },
  messageTextSent: {
    color: '#f0f4ec',
  },
  
  // Failed message bubble
  failedMessageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    marginBottom: 12,
  },
  messageBubbleFailed: {
    backgroundColor: '#8a7a7a',
    opacity: 0.9,
  },
  readReceiptFailed: {
    color: '#ffaaaa',
  },
  failedIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#c45a50',
    justifyContent: 'center',
    alignItems: 'center',
  },
  failedIconText: {
    color: '#fff',
    fontFamily: 'Courier',
    fontSize: 14,
    fontWeight: '700',
  },
  
  // Typing indicator bubble
  typingBubble: {
    alignSelf: 'flex-start',
    backgroundColor: '#e1e5da',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 15,
    borderTopLeftRadius: 2,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  typingDots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  typingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#8a9a8a',
  },
  typingDot1: {
    opacity: 0.4,
  },
  typingDot2: {
    opacity: 0.6,
  },
  typingDot3: {
    opacity: 0.8,
  },

  photoMessage: {
    alignSelf: 'flex-start',
    backgroundColor: '#e1e5da',
    padding: 6,
    borderRadius: 12,
    borderTopLeftRadius: 2,
    marginBottom: 12,
    maxWidth: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  photoFrame: {
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#ced3c7',
  },
  photoImage: {
    width: width * 0.7,
    height: width * 0.5,
    opacity: 0.9,
  },
  photoTime: {
    fontFamily: 'Courier',
    fontSize: 9,
    color: '#8a9a8a',
    marginTop: 4,
  },
  photoCaption: {
    fontFamily: 'Courier',
    fontSize: 13,
    color: '#3a4a3a',
    marginTop: 8,
    marginHorizontal: 4,
    lineHeight: 17,
  },

  // Input bar
  inputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 12,
  },
  inputField: {
    flex: 1,
    height: 44,
    backgroundColor: '#e1e5da',
    borderRadius: 22,
    paddingHorizontal: 16,
    justifyContent: 'center',
    // Subtle inset shadow effect
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.06)',
    borderLeftColor: 'rgba(0, 0, 0, 0.04)',
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.6)',
    borderRightColor: 'rgba(255, 255, 255, 0.5)',
  },
  inputPlaceholder: {
    fontFamily: 'Courier',
    fontSize: 13,
    color: '#8a9a8a',
  },
  inputFieldActive: {
    backgroundColor: '#f8fbf6',
    // Focus glow effect
    borderTopColor: '#5a7a5a',
    borderLeftColor: '#5a7a5a',
    borderBottomColor: '#8aaa8a',
    borderRightColor: '#8aaa8a',
    shadowColor: '#6a8a6a',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  inputText: {
    fontFamily: 'Courier',
    fontSize: 13,
    color: '#3a4a3a',
  },
  cursor: {
    color: '#4a5d4a',
    fontWeight: '300',
  },
  cursorHidden: {
    opacity: 0,
  },
  sendButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#b8beb2',
    justifyContent: 'center',
    alignItems: 'center',
    // 3D raised effect
    shadowColor: '#2a3a2a',
    shadowOffset: { width: 3, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 6,
    // Bevel
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderTopColor: 'rgba(255, 255, 255, 0.5)',
    borderLeftColor: 'rgba(255, 255, 255, 0.4)',
    borderBottomWidth: 2,
    borderRightWidth: 2,
    borderBottomColor: 'rgba(0, 0, 0, 0.12)',
    borderRightColor: 'rgba(0, 0, 0, 0.08)',
  },
  sendButtonActive: {
    backgroundColor: '#5a7a5a',
  },
  sendButtonPressed: {
    backgroundColor: '#4a6a4a',
    // Deeply pressed state - fully inverted bevel, shadow collapsed
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.2)',
    borderLeftColor: 'rgba(0, 0, 0, 0.15)',
    borderBottomColor: 'rgba(255, 255, 255, 0.5)',
    borderRightColor: 'rgba(255, 255, 255, 0.4)',
    transform: [{ translateY: 3 }, { scale: 0.95 }],
  },
  sendButtonSending: {
    backgroundColor: '#7a9a7a',
  },
  sendButtonFailed: {
    backgroundColor: '#c45a50',
  },
  sendButtonText: {
    fontFamily: 'Courier',
    fontSize: 18,
    color: '#fff',
    fontWeight: '700',
  },
  inputTextContainer: {
    flex: 1,
  },
  inputFieldFailed: {
    borderColor: '#c45a50',
    backgroundColor: '#f5e8e7',
  },
  inputTextFailed: {
    color: '#8a5a5a',
  },
  sendFailedLabel: {
    fontFamily: 'Courier',
    fontSize: 9,
    color: '#c45a50',
    marginTop: 2,
  },

  // The Corporate Alert Overlay - Game UI Aesthetic
  alertContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(10, 12, 15, 0.92)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  alertBox: {
    width: '100%',
    backgroundColor: Theme.colors.bgDark,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    padding: 24,
  },
  alertHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  alertIcon: {
    marginRight: 12,
  },
  alertIconText: {
    fontSize: 20,
    color: Theme.colors.accentWarn,
  },
  alertTitle: {
    fontFamily: Theme.fonts.mono,
    fontSize: 14,
    fontWeight: '700',
    color: Theme.colors.textPrimary,
    letterSpacing: 2,
    textAlign: 'center',
  },
  alertBody: {
    marginBottom: 24,
  },
  alertRow: {
    marginBottom: 12,
    borderLeftWidth: 2,
    borderLeftColor: Theme.colors.textSecondary,
    paddingLeft: 12,
  },
  alertLabel: {
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    color: Theme.colors.textDim,
    marginBottom: 2,
    letterSpacing: 1,
  },
  alertValue: {
    fontFamily: Theme.fonts.mono,
    fontSize: 12,
    color: Theme.colors.textPrimary,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  authenticateButton: {
    borderWidth: 1,
    borderColor: Theme.colors.textPrimary,
    paddingVertical: 14,
    alignItems: 'center',
  },
  authenticateButtonPressed: {
    backgroundColor: 'rgba(127, 184, 216, 0.15)',
  },
  authenticateText: {
    fontFamily: Theme.fonts.mono,
    fontSize: 14,
    fontWeight: '700',
    color: Theme.colors.textPrimary,
    letterSpacing: 2,
  },

  // Takeover transition overlays
  desatOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#2a2a2a',
  },
  interferenceOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#7fb8d8',
  },
  blackoutOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#0a0c0f',
  },
  messagesWrapper: {
    flex: 1,
    backgroundColor: '#d8dcd0',
  },
});