import { StyleSheet } from 'react-native';
import { Theme } from '../../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 2,
    backgroundColor: Theme.colors.bgPanel,
    // CRT inset panel effect
    borderWidth: 2,
    borderTopColor: 'rgba(0,0,0,0.5)',
    borderLeftColor: 'rgba(0,0,0,0.4)',
    borderBottomColor: 'rgba(80,85,95,0.3)',
    borderRightColor: 'rgba(80,85,95,0.25)',
    borderRadius: 3,
    padding: 8,
    // Inset shadow
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 3,
    elevation: 3,
  },
  fingerprintSection: {
    marginBottom: 16,
  },
  fingerprintHeader: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 4,
  },
  headerText: {
    color: Theme.colors.textSecondary,
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    marginBottom: 2,
  },
  fingerprintSlots: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    marginBottom: 6,
  },
  fingerprintContainer: {
    width: 54,
    height: 72,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(10, 12, 15, 0.8)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  fingerprintGrid: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 0.5,
    borderColor: 'rgba(74, 138, 90, 0.2)',
    backgroundColor: 'transparent',
    // Using opacity for a subtle grid look
    opacity: 0.3,
  },
  fingerprintImage: {
    width: '100%',
    height: '100%',
    opacity: 0.7,
    tintColor: '#4a8a5a',
  },
  handprintImage: {
    width: '100%',
    height: '100%',
    opacity: 0.7,
    // No tintColor for JPG handprints
  },
  missingHandOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  missingHandText: {
    color: Theme.colors.textDim,
    fontFamily: Theme.fonts.mono,
    fontSize: 32,
    fontWeight: '700',
    letterSpacing: 2,
  },
  flippedFingerprint: {
    transform: [{ scaleX: -1 }],
  },
  scanLine: {
    position: 'absolute',
    width: '100%',
    height: 2,
    backgroundColor: Theme.colors.accentApprove,
    shadowColor: Theme.colors.accentApprove,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 4,
    elevation: 5,
  },
  scanningCircle: {
    position: 'absolute',
    borderWidth: 1,
    borderColor: 'rgba(74, 138, 90, 0.8)',
    borderRadius: 100,
  },
  minutiaeContainer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  minutiaeDot: {
    position: 'absolute',
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: '#d4534a', // accentDeny
    zIndex: 10,
  },
  minutiaeCircle: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 0.5,
    borderColor: '#d4534a',
    backgroundColor: 'rgba(212, 83, 74, 0.1)',
  },
  minutiaeLine: {
    position: 'absolute',
    height: 0.5,
    backgroundColor: '#d4534a',
    opacity: 0.6,
  },
  minutiaeText: {
    position: 'absolute',
    color: '#d4534a',
    fontFamily: Theme.fonts.mono,
    fontSize: 5,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  matchSection: {
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: 8,
  },
  sexColumn: {
    flex: 0.8,
  },
  bpmColumn: {
    flex: 1,
    alignItems: 'center',
    minWidth: 50,
    maxWidth: 70,
    marginHorizontal: 2,
  },
  bpmRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 2,
    marginTop: 1,
  },
  bpmText: {
    color: Theme.colors.textPrimary,
    fontFamily: Theme.fonts.mono,
    fontSize: 13,
    fontWeight: '700',
  },
  stabilityText: {
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  confidenceText: {
    color: Theme.colors.textDim,
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
  },
  pulseDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Theme.colors.accentDeny,
  },
  label: {
    color: Theme.colors.textSecondary,
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    marginBottom: 5,
  },
  matchIndicators: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
    gap: 10,
  },
  indicator: {
    width: 22,
    height: 22,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    borderBottomColor: 'rgba(0,0,0,0.4)',
    borderRightColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 2,
  },
  activeIndicator: {
    borderColor: Theme.colors.textPrimary,
  },
  indicatorText: {
    color: Theme.colors.textDim,
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
  },
  activeIndicatorText: {
    color: Theme.colors.textPrimary,
    fontWeight: '700',
  },
  monitorSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingHorizontal: 6,
    marginTop: -2,
    marginBottom: 6,
    gap: 12,
  },
  monitorGroup: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  tapeLabel: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: '#e6e0d6',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.5)',
    marginBottom: 6,
    opacity: 0.92,
    transform: [{ rotate: '-1deg' }],
  },
  tapeLabelText: {
    color: '#000',
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  sexLightsRow: {
    flexDirection: 'row',
    gap: 6,
    paddingVertical: 2,
  },
  sexLight: {
    width: 24,
    height: 24,
    borderRadius: 3,
    backgroundColor: Theme.colors.knobBase,
    borderWidth: 1,
    borderColor: Theme.colors.knobHighlight,
    borderBottomColor: '#1a1d23',
    borderRightColor: '#1a1d23',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sexLightActive: {
    backgroundColor: Theme.colors.buttonYellow,
    borderColor: '#fff4c2',
  },
  sexLightText: {
    color: Theme.colors.textDim,
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    fontWeight: '700',
  },
  sexLightTextActive: {
    color: '#000',
  },
  bpmScreen: {
    width: 78,
    height: 36,
    backgroundColor: '#050708', // Deep CRT black
    // CRT screen inset effect
    borderWidth: 2,
    borderTopColor: 'rgba(0,0,0,0.7)',
    borderLeftColor: 'rgba(0,0,0,0.6)',
    borderBottomColor: 'rgba(60,65,75,0.4)',
    borderRightColor: 'rgba(60,65,75,0.35)',
    borderRadius: 3,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    // Subtle inner glow
    shadowColor: 'rgba(80, 200, 120, 0.2)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  screenStatic: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  bpmScreenInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  bpmScreenValue: {
    color: Theme.colors.textPrimary,
    fontFamily: Theme.fonts.mono,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  bpmScreenUnit: {
    color: Theme.colors.textDim,
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    letterSpacing: 1,
    marginTop: 2,
  },
  monitorLabel: {
    color: Theme.colors.textDim,
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    letterSpacing: 1,
    fontWeight: '700',
  },
  visualizer: {
    marginTop: 'auto',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
  },
  visualizerText: {
    color: Theme.colors.textDim,
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    letterSpacing: 1,
  },
  // Phase 5: Ambiguous condition styles
  ambiguousContainer: {
    backgroundColor: 'rgba(255, 107, 53, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 53, 0.4)',
    padding: 6,
    marginTop: 8,
    marginHorizontal: 4,
  },
  ambiguousLabel: {
    color: '#FF6B35',
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  ambiguousMedical: {
    color: Theme.colors.accentApprove,
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    opacity: 0.9,
  },
  ambiguousSuspicious: {
    color: Theme.colors.accentDeny,
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    opacity: 0.9,
    marginTop: 2,
  },
});
