import { StyleSheet } from 'react-native';
import { Theme } from '../constants/theme';

export const deviceStyles = StyleSheet.create({
  root: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: '#0a0c0f',
  },
  deviceBody: {
    flex: 1,
    margin: 16,
    borderRadius: 16,
    backgroundColor: '#2c2f36',
    padding: 12,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#1b1f26',
  },
  textureLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.85,
  },
  textureMap: {
    width: '100%',
    height: '100%',
  },
  depthShadowLeft: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 12,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  depthShadowRight: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 12,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  depthShadowBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 12,
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  bevelHighlightTop: {
    position: 'absolute',
    top: 0,
    left: 12,
    right: 12,
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  bevelHighlightLeft: {
    position: 'absolute',
    left: 0,
    top: 12,
    bottom: 12,
    width: 2,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  bevelShadowBottom: {
    position: 'absolute',
    bottom: 0,
    left: 12,
    right: 12,
    height: 2,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  bevelShadowRight: {
    position: 'absolute',
    right: 0,
    top: 12,
    bottom: 12,
    width: 2,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  topSection: {
    height: 64,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  handleContainer: {
    width: 70,
    height: 28,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#1b1f26',
    backgroundColor: '#3a3f48',
  },
  topClipContainer: {
    width: 40,
    height: 18,
    borderRadius: 6,
    backgroundColor: '#2a2f36',
  },
  antennaSection: {
    width: 50,
    height: 64,
    borderRadius: 8,
    backgroundColor: '#2a2f36',
  },
  ventGrilleContainer: {
    position: 'absolute',
    right: 10,
    top: 80,
    width: 36,
    height: 90,
  },
  ventGrilleInner: {
    flex: 1,
    justifyContent: 'space-between',
  },
  ventSlot: {
    height: 3,
    backgroundColor: 'rgba(0,0,0,0.45)',
    borderRadius: 2,
  },
  screenSection: {
    flex: 1,
    marginTop: 8,
    marginBottom: 12,
  },
  screenOuterFrame: {
    flex: 1,
    borderRadius: 12,
    padding: 6,
    backgroundColor: '#1c2027',
  },
  screenInnerFrame: {
    flex: 1,
    borderRadius: 10,
    padding: 6,
    backgroundColor: '#111317',
  },
  screenBezel: {
    flex: 1,
    borderRadius: 8,
    padding: 6,
    backgroundColor: '#0c0f14',
  },
  lcdScreen: {
    flex: 1,
    borderRadius: 6,
    backgroundColor: '#0a0c10',
    overflow: 'hidden',
  },
  screenGlow: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(120, 160, 140, 0.05)',
  },
  screenVignetteTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 24,
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  screenVignetteBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 24,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  screenVignetteLeft: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 16,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  screenVignetteRight: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 16,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  scanlinesOverlay: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.08,
  },
  scanline: {
    height: 2,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.4)',
  },
  screenReflection: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '18%',
    backgroundColor: 'rgba(255,255,255,0.02)',
  },
  terminalContainer: {
    flex: 1,
    padding: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  acronymBlock: {
    alignItems: 'center',
  },
  acronymTitle: {
    fontFamily: Theme.fonts.mono,
    fontSize: 18,
    color: '#5aba6a',
    letterSpacing: 4,
  },
  acronymPhrase: {
    marginTop: 4,
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    color: '#4a8a5a',
  },
  terminalTextWrapper: {
    marginTop: 12,
  },
  terminalGreen: {
    color: '#5aba6a',
  },
  ledContainer: {
    position: 'absolute',
    right: 16,
    bottom: 16,
  },
  ledMount: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#0d1014',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ledLight: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#40ff7a',
  },
  ledOff: {
    backgroundColor: '#1b3324',
  },
  screenLabelRow: {
    position: 'absolute',
    top: 10,
    left: 16,
    right: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  screenLabel: {
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    color: Theme.colors.textDim,
    letterSpacing: 2,
  },
  screenLabelLeft: {
    color: Theme.colors.textPrimary,
  },
  brandSection: {
    alignItems: 'center',
    marginBottom: 8,
  },
  brandText: {
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    color: Theme.colors.textDim,
    letterSpacing: 4,
  },
  bottomSection: {
    marginTop: 8,
    height: 260,
    position: 'relative',
  },
  hiddenButtonsContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 200,
    backgroundColor: 'rgba(27, 31, 38, 0.98)',
    borderRadius: 10,
    padding: 10,
    zIndex: 1,
  },
  hiddenButtonsCavity: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#0f1216',
  },
  hiddenButtonsCavityShadow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  hiddenButtonsLabel: {
    alignSelf: 'center',
    marginBottom: 8,
  },
  hiddenButtonsLabelText: {
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    color: Theme.colors.textSecondary,
    letterSpacing: 2,
  },
  hiddenButtonsWarningStripe: {
    position: 'absolute',
    top: 6,
    right: 12,
    width: 40,
    height: 4,
    backgroundColor: 'rgba(255, 180, 60, 0.5)',
  },
  hiddenButtonBezel: {
    marginBottom: 8,
  },
  hiddenButtonBezelInner: {
    position: 'absolute',
    left: 2,
    right: 2,
    top: 2,
    bottom: 2,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#14171c',
  },
  hiddenButton: {
    backgroundColor: '#2c313a',
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
  },
  hiddenButtonPressed: {
    backgroundColor: '#232730',
  },
  hiddenButtonHighlight: {
    position: 'absolute',
    top: 2,
    left: 6,
    right: 6,
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  hiddenButtonShadow: {
    position: 'absolute',
    bottom: 2,
    left: 6,
    right: 6,
    height: 2,
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  hiddenButtonInset: {
    position: 'absolute',
    inset: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#1a1e25',
  },
  hiddenButtonLabel: {
    fontFamily: Theme.fonts.mono,
    fontSize: 12,
    color: Theme.colors.textPrimary,
    letterSpacing: 2,
  },
  hiddenButtonIndicator: {
    position: 'absolute',
    right: 8,
    top: 8,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#1b1f26',
  },
  hiddenButtonIndicatorActive: {
    backgroundColor: '#4cff8b',
  },
  slidingPanel: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 200,
    backgroundColor: '#1a1e26',
    borderRadius: 10,
    justifyContent: 'flex-end',
    paddingHorizontal: 12,
    paddingBottom: 12,
    zIndex: 10,
    overflow: 'hidden',
  },
  slidingPanelTextureWrapper: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  slidingPanelMetalTexture: {
    position: 'absolute',
    top: '-25%',
    left: '-25%',
    width: '150%',
    height: '150%',
    opacity: 0.5,
  },
  slidingPanelHighlight: {
    position: 'absolute',
    top: 4,
    left: 12,
    right: 12,
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  slidingPanelLabelEmboss: {
    position: 'absolute',
    left: 12,
    top: 10,
  },
  slidingPanelLabelText: {
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    color: Theme.colors.textDim,
    letterSpacing: 2,
  },
  slideHandle: {
    alignItems: 'center',
  },
  slideHandleBar: {
    width: 90,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#2b3038',
  },
  slideHandleBarHighlight: {
    position: 'absolute',
    top: 1,
    left: 4,
    right: 4,
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  slideHint: {
    marginTop: 6,
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    color: Theme.colors.textDim,
    letterSpacing: 2,
  },
});
