import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#d8dcd0', // Desaturated greenish-grey - bland/comfy dystopian
  },
  
  // ============= STATUS BAR =============
  statusBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  statusTime: {
    fontFamily: 'Courier',
    fontSize: 14,
    fontWeight: '600',
    color: '#3a4a3a',
  },
  statusRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  signalBars: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 2,
  },
  signalBar: {
    width: 3,
    backgroundColor: '#4a5d4a',
    borderRadius: 1,
  },
  signalBar1: { height: 4 },
  signalBar2: { height: 7 },
  signalBar3: { height: 10 },
  signalBar4: { height: 13, opacity: 0.3 },
  batteryText: {
    fontFamily: 'Courier',
    fontSize: 12,
    color: '#4a5d4a',
  },

  // ============= MENU SCREEN =============
  menuContainer: {
    flex: 1,
  },
  menuContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    paddingBottom: 80,
  },
  logoContainer: {
    marginBottom: 30,
  },
  logoRing: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#d8dcd0',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#4a5d4a',
    shadowColor: '#000',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
  },
  logoInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#e1e5da',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(74, 93, 74, 0.2)',
  },
  logoText: {
    fontFamily: 'Courier',
    fontSize: 28,
    fontWeight: '700',
    color: '#4a5d4a',
  },
  menuTitle: {
    fontFamily: 'Courier',
    fontSize: 24,
    fontWeight: '700',
    color: '#3a4a3a',
    letterSpacing: 4,
    marginBottom: 6,
    textAlign: 'center',
  },
  menuSubtitle: {
    fontFamily: 'Courier',
    fontSize: 9,
    color: '#6a7a6a',
    letterSpacing: 2,
    marginBottom: 4,
    textAlign: 'center',
    opacity: 0.8,
  },
  menuVersion: {
    fontFamily: 'Courier',
    fontSize: 10,
    color: '#8a9a8a',
    marginBottom: 40,
  },
  startButton: {
    width: 180,
    height: 55,
    backgroundColor: '#d8dcd0',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    marginBottom: 30,
  },
  startButtonInner: {
    width: '94%',
    height: '86%',
    borderRadius: 8,
    backgroundColor: '#e1e5da',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.03)',
  },
  startButtonText: {
    fontFamily: 'Courier',
    fontSize: 16,
    fontWeight: '700',
    color: '#3a4a3a',
    letterSpacing: 4,
  },
  footerText: {
    fontFamily: 'Courier',
    fontSize: 8,
    color: '#8a9a8a',
    letterSpacing: 1,
  },

  // ============= MESSAGES SCREEN =============
  onboardContainer: {
    flex: 1,
  },
  
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(74, 93, 74, 0.1)',
    backgroundColor: '#e1e5da',
  },
  avatarContainer: {
    position: 'relative',
    marginRight: 12,
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#b8c4b0',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#d8dcd0',
  },
  avatarText: {
    fontFamily: 'Courier',
    fontSize: 18,
    fontWeight: '700',
    color: '#4a5d4a',
  },
  onlineIndicator: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#6a9a6a',
    borderWidth: 2,
    borderColor: '#e1e5da',
  },
  headerText: {
    flex: 1,
  },
  contactName: {
    fontFamily: 'Courier',
    fontSize: 16,
    fontWeight: '700',
    color: '#3a4a3a',
  },
  contactStatus: {
    fontFamily: 'Courier',
    fontSize: 11,
    color: '#6a9a6a',
    marginTop: 1,
  },

  timestampContainer: {
    alignItems: 'center',
    paddingVertical: 12,
  },
  timestampText: {
    fontFamily: 'Courier',
    fontSize: 11,
    color: '#8a9a8a',
    backgroundColor: '#e1e5da',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 10,
  },

  messagesArea: {
    flex: 1,
    paddingHorizontal: 16,
  },
  
  messageBubble: {
    alignSelf: 'flex-start',
    backgroundColor: '#e8ebe4',
    paddingHorizontal: 14,
    paddingVertical: 10,
    paddingBottom: 18,
    borderRadius: 16,
    borderTopLeftRadius: 4,
    marginBottom: 8,
    maxWidth: '85%',
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  messageText: {
    fontFamily: 'Courier',
    fontSize: 14,
    color: '#2a3a2a',
    lineHeight: 18,
  },
  messageTime: {
    position: 'absolute',
    bottom: 4,
    right: 10,
    fontFamily: 'Courier',
    fontSize: 9,
    color: '#8a9a8a',
  },

  photoMessage: {
    alignSelf: 'flex-start',
    marginBottom: 8,
    maxWidth: '75%',
  },
  photoFrame: {
    borderRadius: 16,
    borderTopLeftRadius: 4,
    overflow: 'hidden',
    backgroundColor: '#ced3c7',
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  photoImage: {
    width: width * 0.6,
    height: width * 0.45,
  },
  photoTime: {
    fontFamily: 'Courier',
    fontSize: 9,
    color: '#8a9a8a',
    marginTop: 4,
    marginLeft: 4,
  },

  // ============= INPUT BAR =============
  inputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(74, 93, 74, 0.1)',
    backgroundColor: '#e1e5da',
    gap: 10,
  },
  inputField: {
    flex: 1,
    height: 38,
    backgroundColor: '#d8dcd0',
    borderRadius: 19,
    paddingHorizontal: 16,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(74, 93, 74, 0.1)',
  },
  inputPlaceholder: {
    fontFamily: 'Courier',
    fontSize: 13,
    color: '#8a9a8a',
  },
  sendButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#4a5d4a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sendButtonText: {
    fontSize: 16,
    color: '#e1e5da',
    fontWeight: '700',
  },

  // ============= ALERT OVERLAY =============
  alertContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(20, 25, 20, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  alertBox: {
    width: '100%',
    backgroundColor: '#0a0f0a',
    borderWidth: 1,
    borderColor: '#4a5d4a',
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 15,
  },
  alertHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    gap: 10,
  },
  alertIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(138, 154, 138, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  alertIconText: {
    fontSize: 14,
    color: '#8a9a8a',
  },
  alertTitle: {
    fontFamily: 'Courier',
    fontSize: 14,
    fontWeight: '700',
    color: '#8a9a8a',
    letterSpacing: 2,
    textAlign: 'center',
  },
  alertBody: {
    marginBottom: 20,
  },
  alertRow: {
    marginBottom: 10,
    borderLeftWidth: 2,
    borderLeftColor: 'rgba(138, 154, 138, 0.3)',
    paddingLeft: 10,
  },
  alertLabel: {
    fontFamily: 'Courier',
    fontSize: 8,
    color: 'rgba(138, 154, 138, 0.5)',
    marginBottom: 2,
  },
  alertValue: {
    fontFamily: 'Courier',
    fontSize: 11,
    color: '#ccc',
    fontWeight: '600',
    letterSpacing: 1,
  },
  authenticateButton: {
    backgroundColor: 'rgba(138, 154, 138, 0.15)',
    borderWidth: 1,
    borderColor: '#8a9a8a',
    paddingVertical: 14,
    alignItems: 'center',
  },
  authenticateText: {
    fontFamily: 'Courier',
    fontSize: 12,
    fontWeight: '700',
    color: '#8a9a8a',
    letterSpacing: 3,
  },
});
