import { StyleSheet } from 'react-native';
import { Theme } from '../../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 3,
    backgroundColor: Theme.colors.bgDark,
    // CRT monitor frame styling
    borderWidth: 3,
    borderTopColor: 'rgba(80,85,95,0.6)',
    borderLeftColor: 'rgba(80,85,95,0.5)',
    borderBottomColor: 'rgba(15,17,22,0.9)',
    borderRightColor: 'rgba(15,17,22,0.8)',
    padding: 6,
    overflow: 'hidden',
    borderRadius: 4,
    // Bezel shadow
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 3 },
    shadowOpacity: 0.6,
    shadowRadius: 5,
    elevation: 6,
  },
  videoWrapper: {
    flex: 1,
    position: 'relative',
    borderRadius: 6, // CRT screen curvature
    overflow: 'hidden',
    // Inset screen effect
    borderWidth: 2,
    borderTopColor: 'rgba(0,0,0,0.7)',
    borderLeftColor: 'rgba(0,0,0,0.6)',
    borderBottomColor: 'rgba(60,65,75,0.3)',
    borderRightColor: 'rgba(60,65,75,0.25)',
    backgroundColor: '#050708', // Deep CRT black
  },
  // CRT effects overlays
  scanlinesOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 30,
    pointerEvents: 'none',
    overflow: 'hidden',
  },
  scanline: {
    width: '100%',
    height: 2,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  vignetteOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 31,
    pointerEvents: 'none',
    borderRadius: 6,
    borderWidth: 20,
    borderColor: 'rgba(0,0,0,0.25)',
  },
  glassReflection: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '35%',
    zIndex: 32,
    pointerEvents: 'none',
  },
  phosphorGlow: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(80, 200, 120, 0.02)',
    zIndex: 3,
    pointerEvents: 'none',
  },
  video: {
    width: '100%',
    height: '100%',
  },
  zoomContainer: {
    width: '100%',
    height: '100%',
  },
  staticOverlay: {
    ...StyleSheet.absoluteFillObject,
    opacity: .2,
    zIndex: 5,
  },
  laserLine: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: Theme.colors.accentWarn,
    zIndex: 8,
  },
  irisScanLine: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: Theme.colors.accentApprove,
    shadowColor: Theme.colors.accentApprove,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 4,
    zIndex: 9,
  },
  eyeScannerLaser: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: Theme.colors.accentWarn,
    shadowColor: Theme.colors.accentWarn,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 6,
    zIndex: 10,
  },
  holdTint: {
    backgroundColor: 'rgba(201, 162, 39, 0.12)',
    zIndex: 9,
  },
  holdProgressTrack: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 10,
    height: 6,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(201, 162, 39, 0.35)',
    zIndex: 14,
  },
  holdProgressFill: {
    height: '100%',
    backgroundColor: Theme.colors.accentWarn,
  },
  gridOverlay: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.2,
    zIndex: 10,
  },
  gridLine: {
    position: 'absolute',
    backgroundColor: Theme.colors.grid,
  },
  verticalLine: {
    width: 1,
    height: '100%',
  },
  horizontalLine: {
    width: '100%',
    height: 1,
  },
  reticle: {
    position: 'absolute',
    top: '25%',
    left: '25%',
    width: '50%',
    height: '50%',
    borderWidth: 1,
    borderColor: Theme.colors.accentWarn,
    opacity: 0.5,
  },
  reticleCorner: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderColor: Theme.colors.accentWarn,
    borderWidth: 2,
  },
  topLeft: { top: -2, left: -2, borderBottomWidth: 0, borderRightWidth: 0 },
  topRight: { top: -2, right: -2, borderBottomWidth: 0, borderLeftWidth: 0 },
  bottomLeft: { bottom: -2, left: -2, borderTopWidth: 0, borderRightWidth: 0 },
  bottomRight: { bottom: -2, right: -2, borderTopWidth: 0, borderLeftWidth: 0 },
  labelContainer: {
    position: 'absolute',
    bottom: 10,
    alignSelf: 'center',
    zIndex: 15,
  },
  labelBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Theme.colors.bgDark,
    opacity: 0.7,
  },
  labelText: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  circularContainer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  circularBorder: {
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 1,
    borderColor: 'rgba(201, 162, 39, 0.3)',
    borderStyle: 'dashed',
  },
  eyeOverlay: {
    backgroundColor: 'transparent',
    zIndex: 6,
  },
  channelButtonContainer: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 20,
  },
  channelToggleButton: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    backgroundColor: 'rgba(26, 42, 58, 0.8)',
    borderWidth: 1,
    borderColor: Theme.colors.textSecondary,
    borderRadius: 2,
    minWidth: 100,
  },
  channelToggleText: {
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    color: Theme.colors.textSecondary,
    letterSpacing: 1,
    fontWeight: '600',
    textAlign: 'center',
  },
  staticLabel: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -75 }, { translateY: -20 }],
    alignItems: 'center',
    zIndex: 20,
  },
  staticLabelBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 12, 15, 0.75)',
    borderWidth: 1,
    borderColor: 'rgba(74, 106, 122, 0.4)',
    borderRadius: 2,
    transform: [{ scaleX: 1.1 }, { scaleY: 1.25 }],
  },
  staticText: {
    fontFamily: Theme.fonts.mono,
    fontSize: 14,
    color: Theme.colors.textDim,
    letterSpacing: 2,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 4,
  },
  staticSubtext: {
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    color: Theme.colors.textDim,
    letterSpacing: 1,
    fontWeight: '400',
    textAlign: 'center',
    opacity: 0.7,
  },
  identityScanMarker: {
    position: 'absolute',
  },
  redLine: {
    width: '100%',
    height: 2,
    backgroundColor: Theme.colors.accentDeny,
    shadowColor: Theme.colors.accentDeny,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 3,
  },
  redDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Theme.colors.accentDeny,
    shadowColor: Theme.colors.accentDeny,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  idCompletedStamp: {
    position: 'absolute',
    top: '60%',
    left: '50%',
    transform: [{ translateX: -60 }, { translateY: -15 }],
    zIndex: 13,
  },
  idCompletedStampBorder: {
    borderWidth: 2,
    borderColor: Theme.colors.accentApprove,
    backgroundColor: 'rgba(74, 138, 90, 0.15)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 2,
  },
  idCompletedText: {
    fontFamily: Theme.fonts.mono,
    fontSize: 12,
    color: Theme.colors.accentApprove,
    letterSpacing: 2,
    fontWeight: '700',
    textAlign: 'center',
  },
  eyeScannerHint: {
    position: 'absolute',
    bottom: 18,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 14,
  },
  eyeScannerHintBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(201, 162, 39, 0.5)',
    backgroundColor: 'rgba(10, 12, 15, 0.75)',
    borderRadius: 2,
  },
  eyeScannerHintText: {
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    letterSpacing: 1,
    fontWeight: '700',
    color: Theme.colors.accentWarn,
  },
});
