import { StyleSheet } from 'react-native';
import { Theme } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
    minHeight: 220, // Increased height to accommodate question and response
    flex: 1, // Utilize available space
  },
  mainRow: {
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  actionButton: {
    flex: 1,
    height: 50,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  verifyButton: {
    borderColor: Theme.colors.accentWarn,
    backgroundColor: 'rgba(201, 162, 39, 0.1)',
  },
  dossierButton: {
    borderColor: Theme.colors.textSecondary,
    backgroundColor: 'rgba(127, 184, 216, 0.1)',
  },
  dossierButtonLarge: {
    // The dossier card is a single-button view; make this a real tap target.
    flex: 0,
    alignSelf: 'stretch',
    height: 72,
  },
  dossierPreview: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(74, 106, 122, 0.35)',
    backgroundColor: 'rgba(26, 42, 58, 0.18)',
    padding: 8,
    justifyContent: 'space-between',
  },
  dossierPreviewDisabled: {
    opacity: 0.45,
  },
  dossierPreviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dossierPreviewPhoto: {
    width: 48,
    height: 60,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: 'rgba(10, 12, 15, 0.35)',
  },
  dossierPreviewIdentity: {
    flex: 1,
    gap: 2,
  },
  dossierPreviewName: {
    color: Theme.colors.textPrimary,
    fontFamily: Theme.fonts.mono,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
  },
  dossierPreviewId: {
    color: Theme.colors.textDim,
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    letterSpacing: 1,
  },
  dossierPreviewBody: {
    gap: 4,
    marginTop: 6,
  },
  dossierPreviewRow: {
    flexDirection: 'row',
    gap: 8,
  },
  dossierPreviewLabel: {
    width: 78,
    color: Theme.colors.textDim,
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    letterSpacing: 1,
  },
  dossierPreviewValue: {
    flex: 1,
    color: Theme.colors.textPrimary,
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    letterSpacing: 0.3,
    opacity: 0.92,
  },
  dossierPreviewFooter: {
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: 'rgba(26, 42, 58, 0.35)',
  },
  dossierPreviewHint: {
    color: Theme.colors.textSecondary,
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    letterSpacing: 1,
    opacity: 0.8,
  },
  verificationPreview: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(74, 106, 122, 0.35)',
    backgroundColor: 'rgba(26, 42, 58, 0.14)',
    padding: 8,
    justifyContent: 'space-between',
  },
  verificationPreviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
  },
  verificationPreviewTag: {
    color: Theme.colors.accentWarn,
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  verificationPreviewMeta: {
    color: Theme.colors.textDim,
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    letterSpacing: 1,
  },
  verificationPreviewBody: {
    gap: 6,
    marginTop: 8,
  },
  verificationPreviewRow: {
    flexDirection: 'row',
    gap: 8,
  },
  verificationPreviewLabel: {
    width: 86,
    color: Theme.colors.textDim,
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    letterSpacing: 1,
  },
  verificationPreviewValue: {
    flex: 1,
    color: Theme.colors.textPrimary,
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    letterSpacing: 0.3,
    opacity: 0.92,
  },
  verificationPreviewValueAlert: {
    flex: 1,
    color: Theme.colors.accentWarn,
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    letterSpacing: 0.3,
    opacity: 0.92,
  },
  verificationPreviewFooter: {
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: 'rgba(26, 42, 58, 0.35)',
  },
  verificationPreviewHint: {
    color: Theme.colors.textSecondary,
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    letterSpacing: 1,
    opacity: 0.8,
  },
  interrogateButton: {
    borderColor: Theme.colors.accentApprove,
    backgroundColor: 'rgba(74, 138, 90, 0.1)',
  },
  interrogateRow: {
    flexDirection: 'column',
    gap: 8,
    alignItems: 'stretch',
    marginTop: 6,
    flex: 1,
  },
  interrogateQuestionBox: {
    flex: 1,
    borderWidth: 2,
    borderColor: 'rgba(0, 0, 0, 0.5)',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    paddingHorizontal: 10,
    paddingVertical: 10,
    justifyContent: 'center',
    borderRadius: 2,
    position: 'relative',
  },
  interrogateQuestionLabel: {
    color: Theme.colors.textSecondary,
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    fontWeight: '700',
    letterSpacing: 1.2,
    position: 'absolute',
    top: 4,
    right: 6,
    opacity: 0.85,
  },
  interrogateQuestionText: {
    color: Theme.colors.accentApprove,
    fontFamily: Theme.fonts.mono,
    fontSize: 12,
    lineHeight: 18,
    flexShrink: 1,
    paddingRight: 18,
  },
  interrogateQuestionTextDisabled: {
    color: Theme.colors.textDim,
    opacity: 0.85,
  },
  interrogateActionRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 'auto',
  },
  interrogateActionButton: {
    flex: 1,
    height: 40,
  },
  interrogateClarifyButton: {
    borderColor: Theme.colors.textSecondary,
    backgroundColor: 'rgba(127, 184, 216, 0.12)',
  },
  interrogateClarifyButtonText: {
    color: Theme.colors.textSecondary,
  },
  interrogateContestButton: {
    borderColor: Theme.colors.accentWarn,
    backgroundColor: 'rgba(201, 162, 39, 0.14)',
  },
  interrogateContestButtonText: {
    color: Theme.colors.accentWarn,
  },
  interrogateRecordButton: {
    borderColor: Theme.colors.accentDeny,
    backgroundColor: 'rgba(212, 83, 74, 0.14)',
  },
  interrogateRecordButtonText: {
    color: Theme.colors.accentDeny,
  },
  // Phase 4: Credential request button
  credentialButton: {
    borderColor: Theme.colors.textPrimary,
    backgroundColor: 'rgba(127, 184, 216, 0.15)',
  },
  credentialButtonText: {
    color: Theme.colors.textPrimary,
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
  },
  actionButtonDisabled: {
    opacity: 0.3,
    borderColor: Theme.colors.textDim,
  },
  actionButtonText: {
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
  },
  verifyButtonText: {
    color: Theme.colors.accentWarn,
  },
  dossierButtonText: {
    color: Theme.colors.textSecondary,
  },
  interrogateButtonText: {
    color: Theme.colors.accentApprove,
  },
  actionButtonTextDisabled: {
    color: Theme.colors.textDim,
  },
  // Phase 4: Greeting styles
  greetingLabel: {
    color: Theme.colors.textSecondary,
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 1,
  },
  greetingNotice: {
    flex: 1,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: 'rgba(10, 12, 15, 0.6)',
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  greetingText: {
    color: Theme.colors.textPrimary,
    fontFamily: Theme.fonts.mono,
    fontSize: 12,
    lineHeight: 18,
    fontStyle: 'italic',
  },
  agitatedText: {
    letterSpacing: 0,
  },
  brokenText: {
    letterSpacing: 1,
    opacity: 0.9,
  },
  silentText: {
    color: Theme.colors.textDim,
    fontStyle: 'normal',
  },
  // Phase 4: Credential styles
  credentialItem: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(26, 42, 58, 0.5)',
    paddingBottom: 8,
    marginBottom: 8,
  },
  credentialHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  credentialType: {
    color: Theme.colors.textPrimary,
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  credentialNumber: {
    color: Theme.colors.textSecondary,
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    letterSpacing: 0.6,
    marginTop: 2,
    marginBottom: 4,
    opacity: 0.9,
  },
  credentialDetail: {
    color: Theme.colors.textPrimary,
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    letterSpacing: 0.2,
    marginTop: 2,
    lineHeight: 12,
  },
  credentialExpirationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  credentialWarning: {
    color: Theme.colors.accentDeny,
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 1,
  },
  anomalyBadge: {
    color: Theme.colors.accentWarn,
    fontFamily: Theme.fonts.mono,
    fontSize: 12,
    fontWeight: '700',
  },
  anomalyText: {
    color: Theme.colors.accentWarn,
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    marginTop: 4,
  },
  suspiciousSection: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(201, 162, 39, 0.3)',
  },
  suspiciousLabel: {
    color: Theme.colors.accentWarn,
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    fontWeight: '600',
    letterSpacing: 1,
    marginBottom: 4,
  },
  suspiciousItem: {
    color: Theme.colors.accentWarn,
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    letterSpacing: 0.5,
    opacity: 0.8,
  },
  // Phase 4: Investigation layout styles
  investigationContainer: {
    flex: 1,
  },
  investigationCarousel: {
    flex: 1,
  },
  investigationCard: {
    flex: 1,
    borderWidth: 3,
    borderColor: Theme.colors.industrialGray,
    borderTopColor: '#4e5563',
    borderLeftColor: '#4e5563',
    borderBottomColor: '#1a1d23',
    borderRightColor: '#1a1d23',
    backgroundColor: Theme.colors.bgMechanical,
    padding: 12,
    gap: 6,
    ...Theme.effects.bezel,
  },
  investigationCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(26, 42, 58, 0.35)',
  },
  investigationNavHint: {
    color: Theme.colors.textDim,
    fontFamily: Theme.fonts.mono,
    fontSize: 7,
    letterSpacing: 1,
    opacity: 0.7,
  },
  sectionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 12,
  },
  investigationSection: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  sectionHeader: {
    marginBottom: 6,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(26, 42, 58, 0.3)',
  },
  sectionLabel: {
    color: Theme.colors.textPrimary,
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  sectionHint: {
    color: Theme.colors.textDim,
    fontFamily: Theme.fonts.mono,
    fontSize: 7,
    letterSpacing: 0.3,
    opacity: 0.6,
  },
  responseBox: {
    flex: 1,
    backgroundColor: 'rgba(10, 12, 15, 0.45)',
    borderWidth: 2,
    borderColor: Theme.colors.industrialGray,
    padding: 6,
    marginTop: 6,
  },
  gestureTarget: {
    width: '100%',
    height: 50,
  },
  // Verification: bottom-edge swipe handle (no "button" UI)
  verificationSwipeZone: {
    width: '100%',
    height: 28,
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(201, 162, 39, 0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  verificationSwipeZoneDisabled: {
    opacity: 0.35,
  },
  verificationSwipeGrip: {
    width: 44,
    height: 4,
    borderRadius: 2,
    backgroundColor: Theme.colors.accentWarn,
    opacity: 0.75,
  },
  verificationSwipeProgressFill: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    height: 2,
    backgroundColor: Theme.colors.accentWarn,
  },
  // Verification Folders
  folderContainer: {
    flex: 1,
    marginTop: 10,
    gap: 0,
  },
  folderTabsContainer: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 6,
    alignItems: 'center',
    height: 56,
  },
  folderTab: {
    flex: 1,
    height: 24,
    backgroundColor: 'rgba(26, 42, 58, 0.6)',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 12, // Folder-ear look
    borderWidth: 1,
    borderColor: 'rgba(74, 106, 122, 0.4)',
    borderBottomWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  folderTabActive: {
    height: 30,
    backgroundColor: 'rgba(13, 17, 23, 0.95)',
    borderColor: Theme.colors.accentWarn,
    zIndex: 10,
  },
  folderTabText: {
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    color: Theme.colors.textDim,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  folderTabTextActive: {
    color: Theme.colors.accentWarn,
    fontWeight: '700',
  },
  folderContent: {
    flex: 1,
    backgroundColor: 'rgba(13, 17, 23, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(74, 106, 122, 0.4)',
    padding: 8,
    minHeight: 180,
  },
  folderTerminalScroll: {
    flex: 1,
  },
  folderEmptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    opacity: 0.6,
  },
  folderEmptyText: {
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    color: Theme.colors.textDim,
    textAlign: 'center',
    letterSpacing: 1,
  },

  // Tape-style tabs (replacement UI for VerificationFolders)
  tapeTab: {
    flex: 1,
    height: 50,
    borderWidth: 1,
    borderColor: 'rgba(74, 106, 122, 0.45)',
    backgroundColor: 'rgba(13, 17, 23, 0.70)',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingTop: 7,
    paddingBottom: 6,
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  tapeTabActive: {
    borderColor: Theme.colors.accentWarn,
    backgroundColor: 'rgba(13, 17, 23, 0.92)',
    transform: [{ translateY: -2 }],
  },
  tapeTabComplete: {
    borderColor: 'rgba(74, 138, 90, 0.55)',
  },
  tapeNotch: {
    position: 'absolute',
    right: -1,
    top: 14,
    width: 18,
    height: 22,
    borderLeftWidth: 1,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(74, 106, 122, 0.45)',
    backgroundColor: 'rgba(10, 12, 15, 0.75)',
    borderTopLeftRadius: 3,
    borderBottomLeftRadius: 3,
  },
  tapeNameplate: {
    position: 'absolute',
    right: 20, // leave room for the notch
    top: 6,
    maxWidth: 110,
    height: 18,
    paddingHorizontal: 6,
    borderWidth: 1,
    borderColor: 'rgba(74, 106, 122, 0.35)',
    backgroundColor: 'rgba(10, 12, 15, 0.75)',
    borderRadius: 3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  tapeNameplateActive: {
    borderColor: 'rgba(201, 162, 39, 0.75)',
    backgroundColor: 'rgba(13, 17, 23, 0.85)',
  },
  tapeLabel: {
    color: Theme.colors.textPrimary,
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  tapeLabelActive: {
    color: Theme.colors.accentWarn,
  },
  tapeStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 1,
  },
  tapeStatusDotIdle: {
    borderColor: 'rgba(74, 106, 122, 0.7)',
    backgroundColor: 'rgba(10, 12, 15, 0.9)',
  },
  tapeStatusDotComplete: {
    borderColor: 'rgba(74, 138, 90, 0.9)',
    backgroundColor: 'rgba(74, 138, 90, 0.35)',
  },
  tapeStatusDotActive: {
    borderColor: Theme.colors.accentWarn,
  },
  tapeWindow: {
    height: 18,
    borderWidth: 1,
    borderColor: 'rgba(74, 106, 122, 0.35)',
    backgroundColor: 'rgba(10, 12, 15, 0.55)',
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 6,
    marginTop: 2,
  },
  tapeReel: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'rgba(127, 184, 216, 0.35)',
    backgroundColor: 'rgba(13, 17, 23, 0.55)',
  },
  tapeWindowRidge: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 3,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  tapeSubLabel: {
    color: Theme.colors.textDim,
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    letterSpacing: 1.1,
    opacity: 0.9,
  },
  tapeSubLabelActive: {
    color: Theme.colors.textSecondary,
    opacity: 1,
  },
  tapeMeta: {
    position: 'absolute',
    left: 8,
    bottom: 6,
    color: 'rgba(127, 184, 216, 0.65)',
    fontFamily: Theme.fonts.mono,
    fontSize: 7,
    letterSpacing: 1,
  },
  // Phase 3: Credentials swipe styles removed (automated intake gate)

  // =============================================================================
  // Verification Drawer (physical drawer / hinged door)
  // =============================================================================
  verificationDrawerRoot: {
    flex: 1,
    gap: 10,
    marginTop: 8,
  },
  verificationDrawerViewport: {
    height: 164,
    borderWidth: 1,
    borderColor: 'rgba(201, 162, 39, 0.35)',
    backgroundColor: 'rgba(10, 12, 15, 0.55)',
    overflow: 'hidden', // critical: tight container, no overflow
    position: 'relative',
  },
  verificationDrawerUnderlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 12, 15, 0.1)',
  },
  // Interior dressing: gives the “drawer cavity” a physical read.
  verificationDrawerInterior: {
    ...StyleSheet.absoluteFillObject,
  },
  verificationDrawerInteriorBackplate: {
    ...StyleSheet.absoluteFillObject,
    margin: 8,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.55)',
    backgroundColor: 'rgba(6, 7, 9, 0.55)',
  },
  verificationDrawerRailLeft: {
    position: 'absolute',
    left: 6,
    top: 10,
    bottom: 10,
    width: 6,
    backgroundColor: 'rgba(26, 42, 58, 0.22)',
    borderRightWidth: 1,
    borderRightColor: 'rgba(255,255,255,0.05)',
  },
  verificationDrawerRailRight: {
    position: 'absolute',
    right: 6,
    top: 10,
    bottom: 10,
    width: 6,
    backgroundColor: 'rgba(26, 42, 58, 0.22)',
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(255,255,255,0.05)',
  },
  verificationDrawerLipTop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 10,
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.35)',
  },
  verificationDrawerLipBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 10,
    backgroundColor: 'rgba(0,0,0,0.12)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.04)',
  },
  verificationDrawerCanvasHitbox: {
    flex: 1,
  },
  verificationDrawerDoor: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 164,
  },
  verificationDrawerDoorFace: {
    flex: 1,
    position: 'relative',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(201, 162, 39, 0.18)',
    // Warm brown/bronze door to contrast the HUD blues.
    backgroundColor: 'rgba(60, 42, 26, 0.92)',
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 10,
    justifyContent: 'flex-start',
    gap: 10,
  },
  verificationDrawerDoorTopLeftLabel: {
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    fontWeight: '800',
    color: Theme.colors.textPrimary,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    alignSelf: 'flex-start',
  },
  verificationDrawerDoorBevelOuter: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 1,
    borderColor: 'rgba(255, 236, 200, 0.08)',
  },
  verificationDrawerDoorBevelInner: {
    ...StyleSheet.absoluteFillObject,
    margin: 3,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.42)',
  },
  verificationDrawerDoorGrooveLine: {
    position: 'absolute',
    left: 10,
    right: 10,
    top: 38,
    height: 1,
    backgroundColor: 'rgba(255, 236, 200, 0.06)',
  },
  verificationDrawerDoorOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 12, 15, 0.6)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 18,
    elevation: 12,
  },
  verificationDrawerHandleRow: {
    width: '100%',
    alignItems: 'center',
    paddingTop: 2,
  },
  verificationDrawerHandlePlate: {
    width: 92,
    height: 18,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.62)',
    backgroundColor: 'rgba(46, 32, 20, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 10,
  },
  verificationDrawerHandleInset: {
    width: 62,
    height: 6,
    borderRadius: 3,
    backgroundColor: Theme.colors.accentWarn,
    opacity: 0.75,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.35)',
  },
  verificationDrawerHandleRivetLeft: {
    position: 'absolute',
    left: 10,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.4)',
  },
  verificationDrawerHandleRivetRight: {
    position: 'absolute',
    right: 10,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.4)',
  },
  verificationDrawerDoorTextRow: {
    paddingBottom: 10,
    gap: 3,
  },
  verificationDrawerDoorLabel: {
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    fontWeight: '800',
    color: Theme.colors.textPrimary,
    letterSpacing: 1.3,
    textTransform: 'uppercase',
  },
  verificationDrawerDoorHint: {
    fontFamily: Theme.fonts.mono,
    fontSize: 7,
    color: Theme.colors.textDim,
    letterSpacing: 0.8,
    opacity: 0.8,
    textTransform: 'uppercase',
  },
  verificationDrawerBody: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(74, 106, 122, 0.35)',
    backgroundColor: 'rgba(10, 12, 15, 0.35)',
    padding: 8,
    gap: 8,
    overflow: 'hidden',
  },
  verificationDrawerBodyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(26, 42, 58, 0.35)',
  },
  verificationDrawerClosedNote: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 16,
    opacity: 0.7,
  },
  verificationDrawerClosedText: {
    fontFamily: Theme.fonts.mono,
    fontSize: 9,
    color: Theme.colors.textDim,
    letterSpacing: 0.4,
    textAlign: 'center',
  },
  verificationDrawerContent: {
    flex: 1,
    gap: 10,
  },
  verificationDrawerFilePreview: {
    borderWidth: 1,
    borderColor: 'rgba(201, 162, 39, 0.25)',
    backgroundColor: 'rgba(13, 17, 23, 0.75)',
    padding: 10,
    gap: 6,
  },
  verificationDrawerFilePreviewTitle: {
    fontFamily: Theme.fonts.mono,
    fontSize: 10,
    fontWeight: '700',
    color: Theme.colors.textPrimary,
    letterSpacing: 0.6,
  },
  verificationDrawerFilePreviewSub: {
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    color: Theme.colors.textDim,
    letterSpacing: 0.2,
    opacity: 0.9,
  },
  verificationDrawerFilePreviewRule: {
    height: 1,
    backgroundColor: 'rgba(26, 42, 58, 0.45)',
    marginTop: 2,
    marginBottom: 2,
  },
  verificationDrawerFilePreviewMono: {
    fontFamily: Theme.fonts.mono,
    fontSize: 8,
    color: Theme.colors.textSecondary,
    letterSpacing: 0.2,
    lineHeight: 12,
    opacity: 0.92,
  },
});

